# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ------------------------------------------------
# ckeck static files
# ------------------------------------------------
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=10000']
    -   id: pretty-format-json
        args: [--autofix]

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
    - id: markdownlint
      # ignore line length of makrdownlint
      args: [-r, ~MD013]

# ------------------------------------------------
# ckeck ruby files
# ------------------------------------------------
- repo: https://github.com/mattlqx/pre-commit-ruby
  rev: v1.3.5
  hooks:
  - id: rubocop
  - id: rspec
